//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIdentityConfirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyEmail
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string email { get; set; }
        public string stanowisko { get; set; }
        public string addedById { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
