//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIdentityConfirm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dataDB : DbContext
    {
        public dataDB()
            : base("name=dataDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<UsersCompany> UsersCompany { get; set; }
        public virtual DbSet<Wydzial> Wydzial { get; set; }
        public virtual DbSet<Przelozony> Przelozony { get; set; }
        public virtual DbSet<wypowiedzUser> wypowiedzUser { get; set; }
        public virtual DbSet<zgloszenieNar> zgloszenieNar { get; set; }
        public virtual DbSet<ocenaPrzelozony> ocenaPrzelozony { get; set; }
        public virtual DbSet<ocenaCompany> ocenaCompany { get; set; }
        public virtual DbSet<ratingCompany> ratingCompany { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
        public virtual DbSet<companyEmail> companyEmailSet { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    }
}
