//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIdentityConfirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocenaPrzelozony
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public int przelozonyId { get; set; }
        public int kulturaOs { get; set; }
        public int inteligencja { get; set; }
        public int umiSluchania { get; set; }
        public int przyznanieBlad { get; set; }
        public int cwaniastwo { get; set; }
        public int udzielaniePochwal { get; set; }
        public int umieKomunikowania { get; set; }
        public int radzenieKrytyka { get; set; }
        public int rzetenaWiedza { get; set; }
    }
}
