//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIdentityConfirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ocenaCompany
    {
        public int Id { get; set; }
        public string userId { get; set; }
        public int companyId { get; set; }
        public int awans { get; set; }
        public int uznanie { get; set; }
        public int ksztalcenie { get; set; }
        public int zarobki { get; set; }
        public int atmosfera { get; set; }
        public int uklady_ { get; set; }
        public int mobbing { get; set; }
        public int dodatki { get; set; }
        public int socjal { get; set; }
        public int stres { get; set; }
    }
}
