//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIdentityConfirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersImageWypowiedz
    {
        public int Id { get; set; }
        public byte[] Image { get; set; }
        public int WypowiedzId { get; set; }
        public string UserId { get; set; }
        public byte[] miniImage { get; set; }
    }
}
