//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIdentityConfirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wydzial
    {
        public int Id { get; set; }
        public int CompanyID { get; set; }
        public string Wydzial1 { get; set; }
        public int PrzelozonyId { get; set; }
        public string DodalId { get; set; }
    }
}
