//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCIdentityConfirm
{
    using System;
    using System.Collections.Generic;
    
    public partial class wypowiedzUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wypowiedzUser()
        {
            this.like = 0;
            this.notLike = 0;
        }
    
        public int Id { get; set; }
        public string userId { get; set; }
        public int wydzialId { get; set; }
        public string content { get; set; }
        public int companyId { get; set; }
        public string userImie { get; set; }
        public string userNazwisko { get; set; }
        public bool NameOrLogin { get; set; }
        public string userLogin { get; set; }
        public string dateTime { get; set; }
        public int like { get; set; }
        public int notLike { get; set; }
    }
}
